### ISSUE TITLE
Suggestion: User boto3 Stubber instead of mock

### ISSUE THREAD

**Issue by H4kor** [simonw/s3-credentials#13]
This is just a small suggestion, because I recently worked with boto3.

boto3 includes a stubber. The stubber verifies that your mocked returns conform to the structure of the actual response and has some nice features to check the input of the caller.

https://botocore.amazonaws.com/v1/documentation/api/latest/reference/stubber.html

https://github.com/simonw/s3-credentials/blob/cad8a87e3809b066ea7f15aad99460422f913a19/tests/test_s3_credentials.py#L31

**Comment by simonw** [comment]
I considered that in https://github.com/simonw/s3-credentials/pull/6#issuecomment-958522457 but ended up using Mock because I found it easier to figure out. Would happily review a PR using that stubber though!
